Align panel heights
wtg/Shuttle-Tracker-Web pull request #201
Opened 2022-11-17 21:01 UTC by FloofyPancakes

Closes #188 
Aligned the bottom of the panels

![image](https://user-images.githubusercontent.com/80116509/202558785-e856cbf5-c796-4966-8909-be42514715f7.png)

2022-11-18 21:13 UTC, Isaac-the-Man requested changes
Huge blank space in mobile mode.
![image](https://user-images.githubusercontent.com/29915393/202803377-45ddce33-865b-441b-8d96-29d4ea515619.png)

2022-11-18 21:13 UTC, Isaac-the-Man commented on src/components/Schedule.vue
> +  margin-bottom: 59px;
Don't hard code margin

2022-11-19 03:54 UTC, Gerzer commented
> Huge blank space in mobile mode.
> ![image](https://user-images.githubusercontent.com/29915393/202803377-45ddce33-865b-441b-8d96-29d4ea515619.png)

Is there a way to keep the blank space when the cards are displayed side-by-side but to remove it when they’re stacked (like on mobile)?

2022-11-19 16:09 UTC, Isaac-the-Man commented
> > Huge blank space in mobile mode.
> > ![image](https://user-images.githubusercontent.com/29915393/202803377-45ddce33-865b-441b-8d96-29d4ea515619.png)
> 
> Is there a way to keep the blank space when the cards are displayed side-by-side but to remove it when they’re stacked (like on mobile)?

There should be a way to do that, I'll take a look.

2022-11-20 18:25 UTC, Isaac-the-Man commented
Fixed panel height on mobile devices.

![image](https://user-images.githubusercontent.com/29915393/202919203-f7e51fa1-6128-4d7e-8f68-ffc5f2f6505f.png)

![image](https://user-images.githubusercontent.com/29915393/202919224-1f9bab21-4aae-4ace-a662-680af718204e.png)

2022-11-20 18:31 UTC, merged